FROM ubuntu:18.04

RUN export DEBIAN_FRONTEND=noninteractive; \
    export DEBCONF_NONINTERACTIVE_SEEN=true; \
    apt update -qqy && apt install --no-install-recommends -qqy ffmpeg x264 \
    ca-certificates curl wget tzdata imagemagick libmicrohttpd12 autoconf \
    automake autopoint git build-essential gettext pkgconf libtool libzip-dev \
    libjpeg-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev \
    libavdevice-dev libwebp-dev libmicrohttpd-dev libavformat-dev \
    libavcodec-dev libavutil-dev libswscale-dev libavdevice-dev && \
    git clone https://github.com/Motion-Project/motion.git motion-build && \
    cd motion-build && autoreconf -fiv && \
    ./configure --prefix /motion --exec-prefix /motion && \
    make && make install && cd .. && rm -rf /motion-build && \
    apt purge -qqy autoconf automake autopoint git build-essential gettext \
    pkgconf libtool libzip-dev libjpeg-dev libavformat-dev libavcodec-dev \
    libavutil-dev libswscale-dev libavdevice-dev libwebp-dev libmicrohttpd-dev \
    libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libavdevice-dev && \
    apt autoremove -y && apt autoclean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

VOLUME [ "/motion/config", "/motion/data" ]

RUN if [ ! -f /motion/etc/motion/motion.conf ]; then \
    cp /motion/etc/motion/motion-dist.conf motion/etc/motion/motion.conf; fi && \
    sed -i 's/; target_dir value/target_dir \/motion\/data/' /motion/etc/motion/motion.conf && \
    sed -i 's/; log_file value/log_file \/motion\/log\/motion.log/' /motion/etc/motion/motion.conf && \
    sed -i 's/; pid_file value/pid_file \/run\/motion.pid/' /motion/etc/motion/motion.conf && \
    mv /motion/etc/motion /motion/etc/motion-dist && \
    mkdir -p /motion/log

COPY motion-run /bin/

CMD [ "motion-run" ]
